parameters:
  buildJavaVersion: ""
  containerRegistry: "juniper-container-registry"
  repository: "linux_amd64_agent"

steps:
  # checkout files of the openjdk repo that uses this template
  - checkout: self

  # configure (with jtreg)
  # JTREG_PATH is the path to jtreg 4.2.0 set in the docker image linux_amd64_agent
  - bash: |
      bash configure --with-jtreg=$JTREG_PATH
    displayName: "Build: configure"

  # make jdk and jre
  - bash: |
      make images
    displayName: "Build: make"

  # make run-test
  # Only jdk:tier1 is being tested
  - bash: |
      make run-test TEST=jdk:tier1
    displayName: "Test: jtreg jdk:tier1"
  
  # Set testResultsPath
  # The PublishPipelineArtifact task does NOT allow wildcards in targetPath.
  # Thus, the path must be evaluated before.
  - bash: 
      echo "##vso[task.setvariable variable=testResultsPath]$(echo $(Build.Repository.LocalPath)/build/*/test-results)"
    condition: succeededOrFailed()
    displayName: "Post build: get test-results path"

  # Publish test results as pipeline artifact
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(testResultsPath)'
      artifact: 'test-results'
      publishLocation: 'pipeline'
    condition: succeededOrFailed()
    displayName: "Post Build: publish test-results as artifact" 

