parameters:
  buildJavaVersion: ""
  freetypeUri: "https://buildreqs.blob.core.windows.net/freetype/freetype-2.5.3.tar.gz"

steps:
  - bash: |
      printenv
    displayName: "Windows Build: show all env vars"
    condition: eq(variables['system.debug'], 'true')

  # Use the AdoptOpenJDK build scripts to build the OpenJDK8 binaries.
  - script: |
      IF "${{ parameters.buildJavaVersion }}"=="jdk8u" (
        set TOOLCHAIN_VERSION=2010
        set EXTRA_CONFIGURE_ARGS=
        set EXTRA_OPTION=--freetype-tarball-uri ${{ parameters.freetypeUri }}
      )
      IF "${{ parameters.buildJavaVersion }}"=="jdk11u" (
        set TOOLCHAIN_VERSION=2017
        set EXTRA_CONFIGURE_ARGS=--disable-warnings-as-errors
        set EXTRA_OPTION=
      )
      IF "${{ parameters.buildJavaVersion }}"=="jdk" (
        set TOOLCHAIN_VERSION=2017
        set EXTRA_CONFIGURE_ARGS=--disable-warnings-as-errors
        set EXTRA_OPTION=
      )
      bash.exe -c "./makejdk-any-platform.sh --adoptopenjdk-build-repo $(ADOPT_OPENJDK_BUILD_REPO_URI) --repository $(JAVA_SOURCE_REPO_URI) --branch %JAVA_SOURCE_REPO_BRANCH% -J %JDK_BOOT_DIR% --configure-args '%EXTRA_CONFIGURE_ARGS% --with-debug-level=$(BUILD_DEBUG_LEVEL) --with-toolchain-version=%TOOLCHAIN_VERSION%' -d artifacts --target-file-name microsoft-jdk_$(Agent.OSArchitecture)_$(Agent.OS)_hotspot-$(BUILD_DEBUG_LEVEL)_$(Build.BuildId).tar.gz --no-adopt-patches --disable-adopt-branch-safety %EXTRA_OPTION% ${{ parameters.buildJavaVersion }}"
    displayName: "Windows Build: start makejdk-any-platform process"

  # Upload the produced JDK/JRE binary to the build artifact service.
  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: $(Agent.OS)_$(Agent.OSArchitecture)
      targetPath: "workspace/artifacts"
    displayName: "Windows Build: update JKD/JRE artifact"
