# 
# Build macOS template
#
# It runs the 'configure' and 'make' commands to build the jdk,
# and then uploads the jdk image as artifact for later tests

steps:
  # Run configure to set up the upcoming building process
  - bash: bash configure --with-boot-jdk=$(JDK_BOOT_DIR)
    displayName: "[Build] configure"

  # make JDK/JRE
  - bash: make images
    displayName: "[Build] make"

  # make test-image
  - bash: make test-image
    displayName: "[Build] make test-image"
  
  # Compress JDK image and jtreg library path
  - bash: |
      tar -zvcf $(Pipeline.Workspace)/build.tar.gz \
          build/*/images/jdk \
          build/*/images/test
    condition: succeeded()
    displayName: "[Post build] Compress build"

  # Publish build binaries as build artifact
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)/build.tar.gz'
      artifact: '$(Agent.OS)_$(Agent.OSArchitecture)_build'
      publishLocation: 'pipeline'
    condition: succeeded()
    displayName: "[Post build] Publish build as artifact" 

  

