stages:
  - stage: installer_macOS
    variables:
      skipComponentGovernanceDetection: true
    displayName: "Installer macOS"
    condition: and(
      or(
      not(variables.INSTALLER_PLATFORMS),
      contains(variables.INSTALLER_PLATFORMS, 'macOS')
      ),
      succeeded('build_macOS_binaries')
      )
    dependsOn: build_macOS_binaries
    jobs:
      - job: installer_macOS
        displayName: "Installer macOS"
        pool:
          vmImage: macOS-latest
        steps:
          - template: ./steps/macOS/installer.yml

  - stage: installer_windows
    variables:
      skipComponentGovernanceDetection: true
    displayName: "Installer Windows"
    condition: and(
      or(
      not(variables.INSTALLER_PLATFORMS),
      contains(variables.INSTALLER_PLATFORMS, 'Windows')
      ),
      succeeded('build_windows_binaries')
      )
    dependsOn: build_windows_binaries
    jobs:
      - job: installer_windows
        displayName: "Installer Windows"
        pool:
          vmImage: windows-latest
        steps:
          - template: ./steps/windows/installer.yml
