# 
# Build Linux template
#
# It runs the 'configure' and 'make' commands to build the jdk,
# and then uploads the jdk image as artifact for later tests

steps:
  # Run configure to set up the upcoming building process
  - script: bash.exe -c "bash configure --with-boot-jdk=$(JDK_BOOT_DIR)"
    displayName: "[Build] configure"

  # make JDK/JRE
  - script: bash.exe -c "make images"
    displayName: "[Build] make"

  # make test-image
  - script: bash.exe -c "make test-image"
    displayName: "[Build] make test-image"
  
  # Compress JDK image and jtreg library path
  - script: |
      bash.exe -c "tar -zvcf build.tar.gz build/windows-x86_64-normal-server-release/images/jdk build/windows-x86_64-normal-server-release/images/test"
    condition: succeeded()
    displayName: "[Post build] Compress build"

  # Publish build binaries as build artifact
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)\build.tar.gz'
      artifact: '$(Agent.OS)_$(Agent.OSArchitecture)_build'
      publishLocation: 'pipeline'
    condition: succeeded()
    displayName: "[Post build] Publish build as artifact" 

  

