name: "$(Year:yyyy).$(Month).0.$(BuildID)"

trigger: none

pr: none

schedules:
  # Convert the UTC time to VNC time, so 7AM UTC is 12PM Vancouver time
  # We run this every Tuesday
  - cron: "0 7 * * *"
    displayName: Nightly
    always: true
    branches:
      include:
        - master

jobs:
  - job: sync_dependencies
    displayName: "Sync Dependencies"
    pool:
      vmImage: ubuntu-16.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8.0"

      - checkout: self
        fetchDepth: 1

      - bash: |
          pip install -r ./azure-devops/sync-dependencies/scripts/requirements.txt
        displayName: "pip: install dependencies"

      - bash: |
          python ./azure-devops/sync-dependencies/scripts/sync-dependencies.py
        displayName: "python: run script"
        env:
          AZURE_BLOB_STORAGE_CONNECT_STR: $(AZURE_BLOB_STORAGE_CONNECT_STR)
